[package]
name = "host-provider-contracts"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lints.clippy]
pedantic = "deny"

[dev-dependencies]
aleator = { path = "../aleator" }
consolum = { path = "../consolum" }
faber = { path = "../../../faber/runtime/rust" }
host-kernel = { path = "../host-kernel" }
processus = { path = "../processus" }
solum = { path = "../solum" }
tempus = { path = "../tempus" }
