//! Regex operation rows (RX-10e): the real compiler artifacts for the
//! `corpus/regex` cells the Wasm backend lowers end to end run through the
//! product host and match their checked-in `.expected` oracles (the oracle is
//! the MIR runner's output, so the Wasm host agrees with the reference
//! semantics). The artifacts are regenerated by `radix emit -t wasm-text
//! radix/corpus/regex/<cell>.fab`; each `.expected` is the sibling oracle.
//! The closure form (`replace_each`) has no lowered cell on Wasm yet (its
//! format arity is a separate backend limit), so it is proved by a synthetic
//! module against the host row.

use faber_host_wasm::{RunConfig, RunOutcome, WasmRtV1Host};

fn run_wat(wat: &str) -> RunOutcome {
    let bytes = wat::parse_str(wat).expect("module must parse");
    WasmRtV1Host::new()
        .expect("host init")
        .run(&bytes, &RunConfig::default())
}

fn assert_cell(name: &str, wat: &str, expected: &str) {
    assert_eq!(
        run_wat(wat),
        RunOutcome::Success {
            stdout: expected.to_owned(),
            stderr: String::new(),
        },
        "regex/{name}.fab must run through the product host matching its .expected oracle"
    );
}

#[test]
fn find_cell_matches_expected() {
    assert_cell(
        "find",
        include_str!("fixtures/regex-find.wat"),
        include_str!("fixtures/regex-find.expected"),
    );
}

#[test]
fn find_all_cell_matches_expected() {
    assert_cell(
        "find-all",
        include_str!("fixtures/regex-find-all.wat"),
        include_str!("fixtures/regex-find-all.expected"),
    );
}

#[test]
fn split_cell_matches_expected() {
    assert_cell(
        "split",
        include_str!("fixtures/regex-split.wat"),
        include_str!("fixtures/regex-split.expected"),
    );
}

#[test]
fn replace_cell_matches_expected() {
    assert_cell(
        "replace",
        include_str!("fixtures/regex-replace.wat"),
        include_str!("fixtures/regex-replace.expected"),
    );
}

#[test]
fn escape_cell_matches_expected() {
    assert_cell(
        "escape",
        include_str!("fixtures/regex-escape.wat"),
        include_str!("fixtures/regex-escape.expected"),
    );
}

/// A literal table of three text rows: the pattern `a`, the subject `banana`
/// and the replacement `$a`.
const TABLE: &str = r#"
  (memory (export "memory") 1)
  (data (i32.const 0) "abanana$a")
  (data (i32.const 9) "\00\00\00\00\00\00\00\00\01\00\00\00\00\00\00\00\01\00\00\00\06\00\00\00\00\00\00\00\07\00\00\00\02\00\00\00")
  (global (export "__faber_rt_v1_literal_table_ptr") i32 (i32.const 9))
  (global (export "__faber_rt_v1_literal_table_count") i32 (i32.const 3))
"#;

/// `replace_each` assembles the output from the unmatched text and the
/// replacements only: a replacement is never re-scanned, so a `$` or an `a`
/// inside it stays text.
#[test]
fn replace_each_uses_the_replacements_literally() {
    let wat = format!(
        r#"
(module
  (import "faber_rt_v1" "__faber_rt_v1_regex_from_text" (func $from_text (param i32) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_regex_replace_each" (func $each (param i32 i32 i32) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_array_new" (func $array_new (param i32) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_array_push" (func $array_push (param i32 i64) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_diagnostic_nota_ptr" (func $nota_ptr (param i32)))
  {TABLE}
  (func (export "incipit")
    (local $list i32)
    ;; one replacement per match of `a` over `banana` (three matches)
    (local.set $list (call $array_new (i32.const 14)))
    (local.set $list (call $array_push (local.get $list) (i64.const 2)))
    (local.set $list (call $array_push (local.get $list) (i64.const 2)))
    (local.set $list (call $array_push (local.get $list) (i64.const 2)))
    (call $nota_ptr
      (call $each (call $from_text (i32.const 0)) (i32.const 1) (local.get $list)))
  )
)
"#
    );
    assert_eq!(
        run_wat(&wat),
        RunOutcome::Success {
            stdout: "b$an$an$a\n".to_owned(),
            stderr: String::new(),
        }
    );
}

/// A replacement count that disagrees with the match count is a typed
/// failure, never a plausible default.
#[test]
fn replace_each_count_mismatch_is_a_typed_failure() {
    let wat = format!(
        r#"
(module
  (import "faber_rt_v1" "__faber_rt_v1_regex_from_text" (func $from_text (param i32) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_regex_replace_each" (func $each (param i32 i32 i32) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_array_new" (func $array_new (param i32) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_array_push" (func $array_push (param i32 i64) (result i32)))
  (import "faber_rt_v1" "__faber_rt_v1_diagnostic_nota_ptr" (func $nota_ptr (param i32)))
  {TABLE}
  (func (export "incipit")
    (local $list i32)
    (local.set $list (call $array_new (i32.const 14)))
    (local.set $list (call $array_push (local.get $list) (i64.const 2)))
    (call $nota_ptr
      (call $each (call $from_text (i32.const 0)) (i32.const 1) (local.get $list)))
  )
)
"#
    );
    assert!(matches!(run_wat(&wat), RunOutcome::RuntimeFailure { .. }));
}
